// data.js — loads the three JSON files generated by cmd/webapp-export and
// indexes them for fast lookup. The ported path-finder in pathfinder.js
// consumes the indexes this module builds.

const BLACKLIST = new Set([
  "Budva", "Tivat", "Kotor", "Cetinje", "Perast", "Durmitor",
  "Petrovac", "Ulcinj", "Sveti Stefan", "Becici", "Herceg Novi",
  "Savnik", "Zabljak", "Albania", "Tirana", "Shkoder",
  "Bosnia and Herzegovina", "Sarajevo",
]);

// Approximate per-km distances along the real rail corridor in kilometres.
// Only used by the price estimator — these are NOT the source-of-truth distances.
// Rough real-world figures: Bar–Podgorica ~56 km, Podgorica–Bijelo Polje ~131 km,
// Podgorica–Belgrade Centar ~525 km, Podgorica–Nikšić ~56 km. We approximate
// by summing straight-line distances between stops and multiplying by a small
// tortuosity factor.
const RAIL_KM_FACTOR = 1.18;

export class Db {
  constructor(stations, trains, meta, coords) {
    this.stations = stations;              // [] raw list
    this.trains = trains;                  // [] raw list
    this.meta = meta;                      // meta.json
    this.coords = coords.stations || {};   // { id: { lat, lng, confidence }}

    this.stationById = new Map();
    this.stationByLowerName = new Map();
    for (const s of stations) {
      this.stationById.set(s.id, s);
      this.stationByLowerName.set(s.name.toLowerCase(), s);
    }

    this.trainById = new Map();
    this.stationToTrainIds = new Map();
    for (const t of trains) {
      this.trainById.set(t.id, t);
      for (const stop of t.stops) {
        if (!this.stationToTrainIds.has(stop.stationId)) {
          this.stationToTrainIds.set(stop.stationId, new Set());
        }
        this.stationToTrainIds.get(stop.stationId).add(t.id);
      }
    }

    this.transferStationId = meta.transferStationId;

    // Cache main-station list for the "popular routes" UI and map zoom.
    this.mainStations = stations.filter(s => s.type === 4);
  }

  station(id) { return this.stationById.get(id); }
  train(id)   { return this.trainById.get(id); }

  coordOf(stationId) {
    const c = this.coords[String(stationId)];
    return c ? { lat: c.lat, lng: c.lng, confidence: c.confidence } : null;
  }

  isBlacklisted(name) { return BLACKLIST.has(name); }

  // ---- search ----------------------------------------------------------

  // Tiny fuzzy matcher: substring + loose initials. Keeps the prototype
  // self-contained without pulling a full Levenshtein library. The bot
  // itself uses ivanov-gv/approximate-match server-side.
  search(query, { includeAll = false } = {}) {
    const q = normalize(query);
    if (!q) {
      return this.stations
        .filter(s => includeAll || s.type === 4 || s.type === 1)
        .map(s => ({ station: s, score: 0 }));
    }
    const out = [];
    for (const s of this.stations) {
      const name  = normalize(s.name);
      const cyr   = normalize(s.nameCyr);
      const en    = normalize(s.nameEn);
      let score = 0;
      if (name === q || cyr === q || en === q) score = 100;
      else if (name.startsWith(q)) score = 80;
      else if (name.includes(q) || cyr.includes(q) || en.includes(q)) score = 60;
      else if (looseMatch(name, q)) score = 30;
      if (score > 0) out.push({ station: s, score });
    }
    out.sort((a, b) => b.score - a.score
          || a.station.name.localeCompare(b.station.name));
    return out;
  }

  // Distance helpers (used by the price estimator) ------------------------

  haversineKm(aId, bId) {
    const a = this.coordOf(aId), b = this.coordOf(bId);
    if (!a || !b) return null;
    const R = 6371;
    const dLat = toRad(b.lat - a.lat);
    const dLng = toRad(b.lng - a.lng);
    const sa = Math.sin(dLat / 2) ** 2
             + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat))
             * Math.sin(dLng / 2) ** 2;
    return 2 * R * Math.asin(Math.sqrt(sa));
  }

  // Sum of segment distances along a specific train's path between two stops.
  // Falls back to straight haversine if intermediate coords are missing.
  railKm(trainId, fromId, toId) {
    const train = this.train(trainId);
    if (!train) return null;
    const fromIdx = train.stops.findIndex(s => s.stationId === fromId);
    const toIdx   = train.stops.findIndex(s => s.stationId === toId);
    if (fromIdx < 0 || toIdx < 0) return null;
    const [lo, hi] = fromIdx < toIdx ? [fromIdx, toIdx] : [toIdx, fromIdx];
    let total = 0;
    for (let i = lo; i < hi; i++) {
      const seg = this.haversineKm(train.stops[i].stationId, train.stops[i + 1].stationId);
      if (seg == null) { // fallback
        return this.haversineKm(fromId, toId) * RAIL_KM_FACTOR;
      }
      total += seg;
    }
    return total * RAIL_KM_FACTOR;
  }
}

function normalize(s) {
  return (s || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip diacritics
    .trim();
}

function looseMatch(haystack, needle) {
  let i = 0;
  for (const ch of needle) {
    i = haystack.indexOf(ch, i);
    if (i === -1) return false;
    i++;
  }
  return true;
}

function toRad(d) { return (d * Math.PI) / 180; }

export async function loadDb() {
  const [stations, trains, meta, coords] = await Promise.all([
    fetch("data/stations.json").then(r => r.json()),
    fetch("data/trains.json").then(r => r.json()),
    fetch("data/meta.json").then(r => r.json()),
    fetch("data/coordinates.json").then(r => r.json()),
  ]);
  return new Db(stations, trains, meta, coords);
}
