package transfer

import (
	"fmt"
	"os"

	"zpcg/gen/timetable"
	"zpcg/internal/model"
)

const timetableGoFileFormat = `
// Package timetable defines consts for tg-server bot
// Code generated by cmd/exporter. DO NOT EDIT.
package timetable

import (
	"time"

	"zpcg/internal/model"
)

var Timetable = %#v
`

func ExportTimetable(filename string, timetable model.TimetableTransferFormat) error {
	// TODO: the output is not stable - generates different files on the same timetable
	fileContent := fmt.Sprintf(timetableGoFileFormat, timetable)
	file, err := os.OpenFile(filename, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0644)
	defer file.Close()
	if err != nil {
		return fmt.Errorf("can not open file with os.OpenFile: %w", err)
	}
	_, err = file.WriteString(fileContent)
	if err != nil {
		return fmt.Errorf("can not encode timetable with enc.Encode: %w", err)
	}
	return nil
}

func ImportTimetable() model.TimetableTransferFormat {
	return timetable.Timetable
}
