name: ci-pr-checks image build

on:
  workflow_dispatch:
    inputs:
      test_run:
        description: Test run - build without pushing to GHCR
        required: false
        type: boolean


jobs:
  switch:
    name: Test-run switch
    runs-on: ubuntu-latest
    outputs:
      test_run: ${{ steps.test_run.outputs.test_run }}
    steps:
      - uses: actions/checkout@v6
      - id: test_run
        uses: ./.github/actions/test_run
        with:
          test_run: ${{ inputs.test_run }}

  build-and-push:
    name: Build and push CI image
    needs: switch
    if: needs.switch.outputs.test_run != 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env: &build-and-push-env
      IMAGE_TAG: ghcr.io/${{ github.repository }}/ci-pr-checks:${{ vars.TDLIB_COMMIT || '971684a' }}
      TDLIB_COMMIT: ${{ vars.TDLIB_COMMIT || '971684a' }}
    steps: &build-and-push-steps
      - uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build CI image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: deploy/ci-pr-checks.dockerfile
          build-args: TDLIB_COMMIT=${{ env.TDLIB_COMMIT }}
          load: 'true'
          tags: |
            ghcr.io/${{ github.repository }}/ci-pr-checks:${{ env.TDLIB_COMMIT }}

      - name: Push
        if: ${{ needs.switch.outputs.test_run != 'true' }}
        run: docker push ${{ env.IMAGE_TAG }}

  build-and-push-test-run:
    name: Build CI image (test-run)
    needs: switch
    if: needs.switch.outputs.test_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    env: *build-and-push-env
    steps: *build-and-push-steps
