name: Pull request checks

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ github.ref != 'refs/heads/main' && 'ci-pr-checks-approval' || '' }}
    steps:
      - uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build

  test:
    name: Tests
    runs-on: ubuntu-latest
    environment: ${{ github.ref != 'refs/heads/main' && 'ci-pr-checks-approval' || '' }}
    container:
      image: ghcr.io/${{ github.repository }}/ci-pr-checks:${{ vars.TDLIB_COMMIT || '971684a' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
      - name: Run all tests
        run: go test -count=1 -race ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment: ${{ github.ref != 'refs/heads/main' && 'ci-pr-checks-approval' || '' }}
    container:
      image: ghcr.io/${{ github.repository }}/ci-pr-checks:${{ vars.TDLIB_COMMIT || '971684a' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
          args: --timeout=5m ./...

  workflows-lint:
    name: Lint workflows
    runs-on: ubuntu-latest
    environment: ${{ github.ref != 'refs/heads/main' && 'ci-pr-checks-approval' || '' }}
    container:
      image: ghcr.io/${{ github.repository }}/ci-pr-checks:${{ vars.TDLIB_COMMIT || '971684a' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v6
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Lint all workflows
        run: make test-all-workflows ACT="act -n" GCLOUD_TOKEN=no-token
