name: CI - push to ghcr.io
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry run
        type: boolean
        default: true

jobs:
  switch:
    name: Dry-run switch
    runs-on: ubuntu-latest
    outputs:
      dry_run: ${{ steps.dry_run.outputs.dry_run }}
    steps:
      - uses: actions/checkout@v4
      - id: dry_run
        uses: ./.github/actions/dry_run
        with:
          dry_run: ${{ inputs.dry_run }}

  build-and-push:
    name: Build and push ZPCG image
    needs: switch
    if: needs.switch.outputs.dry_run != 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: dev
    env: &build-and-push-env
      IMAGE_TAG_SHA: ${{ vars.ENV_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
      IMAGE_TAG_TAG: ${{ vars.ENV_REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
    steps: &build-and-push-steps
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/Dockerfile
          load: 'true'
          tags: |
            ${{ env.IMAGE_TAG_SHA }}
            ${{ env.IMAGE_TAG_TAG }}

      - name: Push
        run: |
          docker push ${{ env.IMAGE_TAG_SHA }}
          docker push ${{ env.IMAGE_TAG_TAG }}

  build-and-push-dry-run:
    name: Build CI image (dry-run)
    needs: switch
    if: needs.switch.outputs.dry_run == 'true'
    runs-on: ubuntu-latest
    environment: dry-run
    permissions:
      contents: read
      packages: read # <-- dry-run mode
      id-token: write
    env: *build-and-push-env
    steps: *build-and-push-steps

