name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    with:
      commit_sha: ${{ github.sha }}
      push: true
      gcloud_region: ${{ vars.GCLOUD_REGION }}
      gcloud_project_id: ${{ vars.GCLOUD_PROJECT_ID }}

  deploy-preprod:
    name: Deploy to Preprod
    needs: build
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: preprod
      gcloud_image: ${{ needs.build.outputs.gcloud_tag }}
      env_var_environment: ${{ vars.ENV_VAR_ENVIRONMENT }}
      gcloud_project_id: ${{ vars.GCLOUD_PROJECT_ID }}
      gcloud_region: ${{ vars.GCLOUD_REGION }}
      gcloud_run_service: ${{ vars.GCLOUD_RUN_SERVICE }}
      gcloud_secret_version_telegram_token: ${{ vars.GCLOUD_SECRET_TELEGRAM_APITOKEN_VERSION }}

  deploy-production:
    name: Deploy to Production
    needs: [ build, deploy-preprod ]
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: prod
      gcloud_image: ${{ needs.build.outputs.gcloud_tag }}
      env_var_environment: ${{ vars.ENV_VAR_ENVIRONMENT }}
      gcloud_project_id: ${{ vars.GCLOUD_PROJECT_ID }}
      gcloud_region: ${{ vars.GCLOUD_REGION }}
      gcloud_run_service: ${{ vars.GCLOUD_RUN_SERVICE }}
      gcloud_secret_version_telegram_token: ${{ vars.GCLOUD_SECRET_TELEGRAM_APITOKEN_VERSION }}
