name: Deploy to Stage

on:
  workflow_dispatch:
    inputs:
      description:
        description: "What's being deployed"
        required: false
        type: string

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      commit_sha: ${{ github.sha }}
      push: true
  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: preprod
      gcloud_image: ${{ needs.build.outputs.gcloud_image }}

