name: Deploy to Stage

on:
  workflow_dispatch:
    inputs:
      description:
        description: "What's being deployed"
        required: false
        type: string

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    with:
      commit_sha: ${{ github.sha }}
      push: true
      gcloud_region: ${{ vars.GCLOUD_REGION }}
      gcloud_project_id: ${{ vars.GCLOUD_PROJECT_ID }}

  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: preprod
      gcloud_image: ${{ needs.build.outputs.gcloud_tag }}
      env_var_environment: ${{ vars.ENV_VAR_ENVIRONMENT }}
      gcloud_project_id: ${{ vars.GCLOUD_PROJECT_ID }}
      gcloud_region: ${{ vars.GCLOUD_REGION }}
      gcloud_run_service: ${{ vars.GCLOUD_RUN_SERVICE }}